### ISSUE TITLE
questions about convert bytes string to IP address

### ISSUE THREAD

**Issue by xiaopeng163** [drkjam/netaddr#124]
hi 

i have a hex bytes string received from TCP connection.

``` python
a = b'\x10\x10\x10\x10'
```

and i want to convert it to a IP address ``16.16.16.16``. i alway change the bytes string to int and then use:

``` python
str(netaddr.IPAddress(int(binascii.b2a_hex(a, 16)))
```

is there any simple way to do that?

**Comment by snordhausen** [comment]
Hi!

The `struct` module helps you to convert binary data to integers and back:

```
a = b'\x10\x10\x10\x11'
import struct
from netaddr import IPAddress
IPAddress(struct.unpack("!I", a)[0])
```

You need to keep in mind the endianness of the value, though. The example above expects network (=big endian). Use `struct.unpack("<I".....` if you have little endian.

**Comment by tyler-8** [comment]
Reopening because I've wanted this as well.

I think it makes sense that if `netaddr` can provide a `myaddr.packed` output, then it should be able to natively ingest a packed IP address to a `IPAddress()` instance without having to do extra manipulation before passing to netaddr.

`netaddr` could borrow this from the standard library [ipaddress](https://github.com/python/cpython/blob/master/Lib/ipaddress.py#L1905) (IPv6 linked):

        # Constructing from a packed address
        if isinstance(address, bytes):
            self._check_packed_address(address, 16)
            self._ip = int.from_bytes(address, 'big')
            return

**Comment by rosstex** [comment]
bump, this would be a nice feature

**Comment by mortlind** [comment]
I would also like this feature, since I send MAC addresses over the network in packed format in a struct.Struct. I suggest, for symmetry that a classmethod named `.unpack(addr: bytes)` should be implemented on both IPX- and MAC address classes, which would create an object comparing equal to the one from which the bytes were obtained with the property `.packed`.
