### ISSUE TITLE
Support for (IP,Mask) -> CIDR in IPNetwork

### ISSUE THREAD

**Issue by morphyno** [drkjam/netaddr#126]
I'm curious is it possible to set the value of a IP and mask and obtain the cidr output?

Right now netmask and ip attributes are not settable after IPNetwork object is instantiated

>>> ip = IPNetwork('192.168.200.100')
>>> ip.netmask
IPAddress('255.255.255.255')
>>> ip.netmask='255.255.0.0.'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute

**Comment by snordhausen** [comment]
The netmask can be changed indirectly like this:
```
>>> x
IPNetwork('10.0.0.0/16')
>>> x.prefixlen = 24
>>> x
IPNetwork('10.0.0.0/24')
```
But for the most part, these properties are just read-only properties. You would need to create a new IPNetwork object like this:
```
>>> y
IPNetwork('10.0.0.0/8')
>>> IPNetwork("{}/255.255.255.0".format(x.ip))
IPNetwork('10.0.0.0/24')
```

I will leave this ticket open because I think the netmask should actually be writable and it is probably not a lot of effort.

**Comment by nnathan** [comment]
I've started the (simple) groundwork for setting IPNetwork() by netmask. It currently has two issues:
(1) doesn't support IPv6 netmasks
(2) it inadvertently supports setting the number of bits of the netmask (aka prefixlen) via the same property. I don't know if we should care about input validation here.
(3) it lacks any testing/code coverage

Without checking if the existing IPNetwork is an ipv4/ipv6 address, I'm not sure how to support (1).

**Comment by nnathan** [comment]
I pushed a new version here: https://github.com/drkjam/netaddr/pull/128

1. Setting netmask property now supports both IPv4 and IPv6 netmasks and doesn't allow mixing and matching (e.g. `ip = IPAddress('5.5.5.5'); ip.netmask = 'ffff:fffff::'` will fail due to IPv4/IPv6 mismatch.
2. Added tests for setting both netmask and prefixlen.
3. Added docs showing example use.

**Comment by morphyno** [comment]
Thanks, this this great!
