### ISSUE TITLE
Refresh IANA and IEEE Databases

### ISSUE THREAD

**Issue by dmichel1** [drkjam/netaddr#127]
Hello,

Is there a candance for releases of netaddr to keep the IANA and IEEE databases from going out of date?  

I see it's almost been a year since it's been updated and I have an issue with newer ID that was recently added. Shall I open a PR to update the database or is there another process to do so?

Thanks,
Drew

**Comment by thimslugga** [comment]
I've submitted a PR with the updated files. Hopefully it gets accepted.

 https://github.com/drkjam/netaddr/pull/134

**Comment by drkjam** [comment]
I only update the databases when I do a release. As it has been a while since 0.7.18 went out, things have become stale. I will endeavour to provide new releases on a more regular basis to address this, possibly every 3 months or so.

thimslugga - thank you for the pull request. I am not going to accept it in its current form as there are merge conflicts with current changes on the dev branch, I am not keen on accepting changes that aren't supported by tests, and various other required changes (e.g. to the Makefile) are missing. I'm also not keen on pulling in really big updates to data files that I cannot verify the source of.

I am now actively working on ticket #101 part of the milestone for release 0.7.19. Discussion on changes taking place will be on #101; closing this one now to avoid duplication.
