### ISSUE TITLE
IPNetwork v6 with not-matching address and prefix are shown wrong

### ISSUE THREAD

**Issue by xpac1985** [drkjam/netaddr#147]
Hey,
I'd like to report something I'm not perfectly sure if it's on purpose or not.

`>>> IPNetwork("2001:4::/16")
IPNetwork('2001:4::/16')`

Considering the prefix, I thought it would be converted or shown as '2001::/16' only, as only that part is a valid network address with a /16 prefix.

Am I right on that, or do I miss something?

**Comment by drkjam** [comment]
This is a historical aspect of the library which does seem odd to some users when you first encounter it. It has been around since the earliest version of this software and will not be changing.

There are several dynamic properties you can make use of depending on your needs.

1. If you want the network CIDR with the mask applied to the input address specification.

```
>>> IPNetwork('2001:4::/16').cidr
IPNetwork('2001::/16')
```

1. If you want the network IP address only *without* the CIDR prefix.

```
>>> IPNetwork('2001:4::/16').network
IPAddress('2001::')
```

2. If you want the original IP address provided without applying network mask defined by the CIDR prefix.

```
>>> IPNetwork('2001:4::/16').ip
IPAddress('2001:4::')
```
