### ISSUE TITLE
Still some problems parsing MAC Address to manufacturer, updated netaddr

### ISSUE THREAD

**Issue by localtracker** [drkjam/netaddr#91]
Hey,

So since the last issue that I had, I updated my version of netaddr and everything started working right though even now sometimes the OUI cant be resolved and the script stalls. 

OUI 7383024 not registered!

At this point, the script has stopped and given an error. This is the code block:

```
def get_oui(mac):
	global macf
	maco = EUI(mac)
	macf = maco.oui.registration().org
	return macf

def phandle(p):
	global count, vali, pc									  
    	if p.haslayer(Dot11ProbeReq):
		if pc == 0:
			print O+'[+]'+W+' Connections up! Captured our first probe!\n'                         
        	if p.haslayer(Dot11Elt):
			pc +=1
	    		vali = 0	                          
            		if p.ID == 0: 
                		ssid = p.info
				if ssid != "":
					for (i,j) in obs:
						if (i,j) != (p.addr2,ssid):
							vali += 1
						else:
							break
					if vali == len(obs):
						obs.append((p.addr2,ssid))
						checkmac(p.addr2)
						checknet(ssid)
						count +=1
						get_oui(p.addr2)
						print str(count)+'>',p.addr2+' ('+G+macf+W+') <--Probing--> '+O+ssid+W
						wr_log(p.addr2,ssid,macf)	
					else:
						pass
```
This is the exception block setup:
```
except Exception,e:
		call(["rm","temp.pyr"])
		print '\n'+O+'[!]'+W+' Error! Something happened!\n'
        	print str(e)
	except KeyboardInterrupt:
		print '\n'
        	call(["rm","temp.pyr"])
```

How can I catch the error and instead of the script stalling, show a Not available in place of the manufacturer? Also, this does'nt happen everytime the script runs. Sometimes it'll happen after scanning maybe 500 devices and sometimes in some locations it'll start stalling in the first few devices. Till now it has successfully parsed about 8000 devices and about 5-8 in that period it had stalled.

**Comment by snordhausen** [comment]
Since 

>>> EUI('70a7f0424242').oui.registration().org

raises an exception of type netaddr.core.NotRegisteredError, you can do
```python
from netaddr.core import NotRegisteredError
def get_oui(mac):
    global macf
    maco = EUI(mac)
    try:
        macf = maco.oui.registration().org
    except NotRegisteredError:
        macf = "Not available"
    return macf
```


For the phandle function, my advice would be to use proper variable names to make the code more readable. O, obs, p, pc, i, and j are not really a good choice. Not even for a small script.

**Comment by localtracker** [comment]
Thanks a lot for the help, I'll conduct some more tests and let you know if everything is going smooth. Ans yes, I know my choice of variable names are really bad and I am sorry for that. I need to replace all of that asap. Also, I need to learn how to code! Thanks again!

**Comment by localtracker** [comment]
over 6000 devices scanned since I edited the code and no errors so far, I take it all is well. Thanks for the help! Fixed a lot of issues!

**Comment by snordhausen** [comment]
I looked at Sniff_import.py for the good coding practices.

[PEP-8](https://www.python.org/dev/peps/pep-0008/) is the generally accepted style guide for Python. Most notably, you should
 * use 4 spaces as indentation. Your code uses tabs, which will break things for pretty much everyone.
 * never ever use a bare `try: ... except: ...` block, because the bare "except:" also catches stuff like people pressing CTRL+C. Use `try:.... except Exception: ...` instead.
 * not have function names in camel-case like "CreateOrUpdateClient". They should look like create_or_update_client. Some old Python code does not follow that convention, but new code should.
 * not use `from some_module import *`, this makes it difficult to figure out where things are coming from. E.g. your code uses the the sniff() function, but it is difficult to find out where it comes from. With "from scapy.all import sniff", it would be easier to figure out.


Use good variable names instead of comments. E.g. instead of doing

    count = 0 #count of scapy packets processed

you should give your variable a good name:

    scapy_packets_processed = 0

So when somebody sees

    scapy_packets_processed += 1

it is immediately clear what is happening and you do not need comments. Use auto-completion in your favorite IDE so you don't have to type the entire name.

The process() function you have is too big and complex. It should basically look like this:
```python
def process(p):
    global count 
    count += 1
    if count % 10000 == 0:
            print count

    if p.haslayer(ARP):
        do_arp_stuff(p)
    elif p.haslayer(Dot11ProbeReq):
        do_dot11_stuff(p)

    if p.haslayer(Dot11) and p.haslayer(UDP) and p.dst == '224.0.0.251':
       do_224_stuff(p)
```
(of course with proper names for the functions) The actual functionality would be moved into 3 new functions. This makes it very simple to get an overview of what the process() function does, e.g. I instantly see that
* there is no special return value
* the function has 3 cases that get some special special processing.
* the `if p.haslayer(Dot11) ...` check is always performed, there is no `return` that might skip it.


All of this was hard to tell before.

**Comment by localtracker** [comment]
Whoa! Thanks a ton for this. I've been reading the PEP-8 style guide and identifed a ton more that was wrong with my code. I will definitely update my code and let you know and give you the trouble of going through it again, lol. Thanks a lot!
