### ISSUE TITLE
IPSet.__contains__ is about 40 times slower than the equivalent IPRange

### ISSUE THREAD

**Issue by novas0x2a** [drkjam/netaddr#94]
This was kind of surprising to me, and probably not intended. Repro script:

```python
#!/usr/bin/env python

import timeit

COUNT = 50000

setup = '''
import netaddr
r = netaddr.IPRange("172.17.0.3", "172.17.0.254")
s = netaddr.IPSet(r)
INSET="172.17.0.25"
NOT_INSET="192.168.0.25"
'''

def in_ipset():
    print '    IN   IPSET: %s' % timeit.timeit('assert INSET in s', setup=setup, number=COUNT)

def in_iprange():
    print '    IN IPRANGE: %s' % timeit.timeit('assert INSET in r', setup=setup, number=COUNT)

def not_in_ipset():
    print 'NOT IN   IPSET: %s' % timeit.timeit('assert not NOT_INSET in s', setup=setup, number=COUNT)

def not_in_iprange():
    print 'NOT IN IPRANGE: %s' % timeit.timeit('assert not NOT_INSET in r', setup=setup, number=COUNT)


in_ipset()
in_iprange()
not_in_ipset()
not_in_iprange()

print

not_in_iprange()
not_in_ipset()
in_iprange()
in_ipset()
```

Example runtime:

```
    IN   IPSET: 8.31968188286
    IN IPRANGE: 0.185167074203
NOT IN   IPSET: 8.41060614586
NOT IN IPRANGE: 0.173701047897

NOT IN IPRANGE: 0.190999984741
NOT IN   IPSET: 8.39108109474
    IN IPRANGE: 0.173267126083
    IN   IPSET: 8.26405286789
```

**Comment by novas0x2a** [comment]
I should also note that I'd expect the complexity of an IPSet.\__contains__ to be roughly linear on the number of gaps in the range, and since it seems to represent the ranges inside the set as cidrs, that means misaligned ranges will need more cidrs (this above example needs 13 cidrs to represent the range).

However, even if an aligned network is used, say:
```python
r = netaddr.IPRange("172.17.0.0", "172.17.0.255")
s = netaddr.IPSet(r)
```
which results an an IPSet of a single cidr, the results do not change much.

**Comment by drkjam** [comment]
Thanks for raising this. Will get a fix together ASAP.

**Comment by snordhausen** [comment]
>I should also note that I'd expect the complexity of an IPSet.__contains__ to be roughly linear on the number of gaps in the range

The complexity is actually not linear, but constant. You can have millions of IP ranges in the set and performance will not go down, so there's no nasty surprises when you move from testing to production.
However, constant does not mean lightning-fast, as you have seen. The worst performance occurs when you check if an IP address is in the set and it is not, which is exactly what you have benchmarked.

```python
import timeit

COUNT = 50000

setup = '''
from netaddr import IPRange, IPSet
r = IPRange("172.17.0.3", "172.17.0.254")
s = IPSet(r)
s2 = IPSet()
for first in range(255):
    prefix = "%s.17.0." % first
    ip_range = IPRange(prefix + "3", prefix + "254")
    s2.add(ip_range)

NOT_INSET="192.168.0.25"
'''


def not_in_ipset():
    print 'NOT IN   IPSET: %s' % timeit.timeit('assert not NOT_INSET in s', setup=setup, number=COUNT)

def not_in_ipset2():
    print 'NOT IN   IPSET2: %s' % timeit.timeit('assert not NOT_INSET in s2', setup=setup, number=COUNT)

not_in_ipset()
not_in_ipset2()
```
Results are

>>> not_in_ipset()
NOT IN   IPSET: 5.80374693871
>>> not_in_ipset2()
NOT IN   IPSET2: 5.81911087036

Even though the second IPSet has 255 times the number of CIDRs in it, the performance is the same.

But looking at the implementation details, it seems like we could avoid creating a few dozen objects, which should improve performance a lot.

**Comment by snordhausen** [comment]
With commit 7b9093f we now have

>>> in_ipset()
    IN   IPSET: 0.600533008575
>>> in_ipset2()
    IN   IPSET2: 0.597878932953
>>> not_in_ipset()
NOT IN   IPSET: 1.92578887939
>>> not_in_ipset2()
NOT IN   IPSET2: 1.9480240345

So the positive case is 10 times as fast now, the negative case 3 times. The remaining difference to IPRange is simply due to the algorithm that ensures O(1) complexity.

Well spotted, and a good example of why O(1) does not automatically mean it's fast in simple cases.

**Comment by snordhausen** [comment]
Just for the record, this was my test code:
```python
import timeit

COUNT = 50000

setup = '''
from netaddr import IPRange, IPSet
r = IPRange("172.17.0.3", "172.17.0.254")
s = IPSet(r)
s2 = IPSet()
for first in range(255):
    prefix = "%s.17.0." % first
    ip_range = IPRange(prefix + "3", prefix + "254")
    s2.add(ip_range)

INSET="172.17.0.25"
NOT_INSET="192.168.0.25"
'''

def in_ipset():
    print '    IN   IPSET: %s' % timeit.timeit('assert INSET in s', setup=setup, number=COUNT)

def in_ipset2():
    print '    IN   IPSET2: %s' % timeit.timeit('assert INSET in s2', setup=setup, number=COUNT)

def not_in_ipset():
    print 'NOT IN   IPSET: %s' % timeit.timeit('assert not NOT_INSET in s', setup=setup, number=COUNT)

def not_in_ipset2():
    print 'NOT IN   IPSET2: %s' % timeit.timeit('assert not NOT_INSET in s2', setup=setup, number=COUNT)

in_ipset()
in_ipset2()
not_in_ipset()
not_in_ipset2()
```

**Comment by varenc** [comment]
Is this considered fixed?

I'm seeing IPSet being ~20x slower when the IP it's checking is not in the IPSet.  
results from the test initially posted
```
    IN   IPSET: 1.8173533510416746
    IN IPRANGE: 0.32400424702791497
NOT IN   IPSET: 4.676582090964075
NOT IN IPRANGE: 0.27750562800792977
```

This matters to me since in my use case most IPs won't match.

Or am I right that this is the intended behavior? Basically, IPSet is constant time regardless of size, but that just means it needs a larger constant time?  (because needs to check if any prefix of an IP matches the set of prefixs in the IPSet's cidrs dict?)

**Comment by TaaviE** [comment]
Unfortunately I've stumbled upon this same or a very similar issue.

I'm trying to take multiple lists of subnets and output them all so that they do not have overlaps (in the case of four sets: `s1, s2, s3, s4 -> s1 - (s2 | s3 | s4), s2 - (s3 | s4), s3 - s4, s4`). But both IPSet set membership, joins and differences become incredibly slow after a million or so subnets (or single addresses) in them, so that the script does not finish its job in hours on good hardware.

Any suggestions?
